config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # A simple route to go to http://localhost:3000/ask
  get "ask", to: "questions#ask"
  # A simple route to go to http://localhost:3000/answer
  get "answer", to: "questions#answer"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
    # code the action
    # router directs "/ask" to this controller action
    @teams = ["Bayern Munich 73-74", "Inter Milan 64-65", "Ajax 71-72", "Liverpool 83--84", "Real Madrid 59-60", "Manchester United 98-99", "Torino 46-47", "Santos 62-63", "Barcelona 91-92"]
    @query = params["team"]
    if @query.nil? || !@query.empty?
      # @query.downcase doesn't work, we replace to .to_s.downcase
      @teams = @teams.select{|team| team.match?(@query.to_s.downcase.gsub(/\s+/, '')) }
    end
  end

  def answer
    @question = params[:question]
    # debugger
    @answer = stupid_answer(@question.to_s)
  end

  # If the message is I am going to work, the coach will answer Great!
  # If the message has a question mark ? at the end, the coach will answer Silly question, get dressed and go to work!.
  # Otherwise the coach will answer I don't care, get dressed and go to work!
  private

    # bug here
    # ActionController::MissingExactTemplate (QuestionsController#answer is missing a template for request formats: text/html)
    # Solvin problem: I had created a new folder to host answer.html.erb with the name answers.
    # the path was correct but the controller only points to the questions folder as it is called questions_controller.
    # The solution was to host answer.html.erb in the questions folder.
    #another possibility would have been to create a new controller.
  def stupid_answer(question)
    if question == "I am going to work"
      "Great!"
      #debugger
    elsif question.end_with?("?")
      "Silly question, get dressed and go to work!."
    else
      "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" src="../app/assets/syulesheets/application.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <span class="navbar-brand mb-0 h1">A simple Rails application #smileWhileCodding</span>
      </div>
    </nav>
    <%= yield %>
    </div>
  </body>
</html>

app/views/questions/answer.html.erb
<h2><%= @question %></h2>
<p><%= @answer %></p>

<%= link_to'Ask your coach', ask_path %>

app/views/questions/ask.html.erb
<h1>Info page</h1>
<div class="name= forms d-flex bd-highlight">
  <form action="<%= ask_path %>" method="get">
    <input type="text"
      name="team"
      <%# Text inside bar %>
      placeholder="What's your favorite team?"
      <%# Define params %>
      value="<%= params["team"] %>">
      <%# value botton %>
    <input type="submit" value="Choose!">
      <ul>
      <%# take instance variable from questions_controller, iterate each teams %>
      <% @teams.each do |team| %>
        <li><%= team.capitalize %></li>
      <% end %>
    </ul>
  </form>

  <div class="coach-form">
    <form action="/answer">
      <label for="question">Ask to your coach</label>
      <input type="text" id="question" name="question" placeholder="today is a day off?">
      <input type="submit" value="Ask!">
  </form>
  </div>
</div>